fork = false
frame = "buttonless" # buttonless none full
idle = false
maximized = true
no-multigrid = false
theme = "auto"
srgb = false
tabs = false
title-hidden = true
vsync = false
wsl = false

[font]
size = 11
hinting = "full"
normal = ["JetBrainsMono Nerd Font"]